<?php

declare(strict_types=1);

namespace Yiisoft\Db\Oracle;

use Yiisoft\Db\QueryBuilder\AbstractQueryBuilder;
use Yiisoft\Db\Schema\QuoterInterface;
use Yiisoft\Db\Schema\SchemaInterface;

/**
 * Implements the Oracle Server specific query builder.
 */
final class QueryBuilder extends AbstractQueryBuilder
{
    /**
     * @psalm-var string[] $typeMap Mapping from abstract column types (keys) to physical column types (values).
     */
    protected array $typeMap = [
        SchemaInterface::TYPE_PK => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY',
        SchemaInterface::TYPE_UPK => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY UNSIGNED NOT NULL PRIMARY KEY',
        SchemaInterface::TYPE_BIGPK => 'NUMBER(20) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY',
        SchemaInterface::TYPE_UBIGPK => 'NUMBER(20) GENERATED BY DEFAULT AS IDENTITY UNSIGNED NOT NULL PRIMARY KEY',
        SchemaInterface::TYPE_CHAR => 'CHAR(1)',
        SchemaInterface::TYPE_STRING => 'VARCHAR2(255)',
        SchemaInterface::TYPE_TEXT => 'CLOB',
        SchemaInterface::TYPE_TINYINT => 'NUMBER(3)',
        SchemaInterface::TYPE_SMALLINT => 'NUMBER(5)',
        SchemaInterface::TYPE_INTEGER => 'NUMBER(10)',
        SchemaInterface::TYPE_BIGINT => 'NUMBER(20)',
        SchemaInterface::TYPE_FLOAT => 'BINARY_FLOAT',
        SchemaInterface::TYPE_DOUBLE => 'BINARY_DOUBLE',
        SchemaInterface::TYPE_DECIMAL => 'NUMBER(10,0)',
        SchemaInterface::TYPE_DATETIME => 'TIMESTAMP(0)',
        SchemaInterface::TYPE_TIMESTAMP => 'TIMESTAMP(0)',
        SchemaInterface::TYPE_TIME => 'INTERVAL DAY(0) TO SECOND(0)',
        SchemaInterface::TYPE_DATE => 'DATE',
        SchemaInterface::TYPE_BINARY => 'BLOB',
        SchemaInterface::TYPE_BOOLEAN => 'NUMBER(1)',
        SchemaInterface::TYPE_MONEY => 'NUMBER(19,4)',
        SchemaInterface::TYPE_UUID => 'RAW(16)',
        SchemaInterface::TYPE_UUID_PK => 'RAW(16) DEFAULT SYS_GUID() PRIMARY KEY',
    ];

    public function __construct(QuoterInterface $quoter, SchemaInterface $schema)
    {
        $ddlBuilder = new DDLQueryBuilder($this, $quoter, $schema);
        $dmlBuilder = new DMLQueryBuilder($this, $quoter, $schema);
        $dqlBuilder = new DQLQueryBuilder($this, $quoter);
        parent::__construct($quoter, $schema, $ddlBuilder, $dmlBuilder, $dqlBuilder);
    }
}
